spring.application.name=voterauthenticatorsimulator
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vdummyeci@gmail.com
spring.mail.password=iyta vupk kcxp hygw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8